# Use node image
FROM ubuntu:latest

# Change the working dir from /src to /root/app
WORKDIR /home/backend

# Copy all to /app
COPY . .

# Grant permission to sh files
RUN chmod +x /home/backend/install.sh
RUN chmod +x /home/backend/nodejs/scripts/install.sh
RUN chmod +x /home/backend/nodejs/scripts/start.sh
RUN chmod +x /home/backend/python/scripts/install.sh

ENTRYPOINT ["/bin/bash", "-c", "/home/backend/install.sh"]