# Use node image
FROM scratch

# Change the working dir from /src to /root/app
WORKDIR /backend

# Copy all to /app
COPY . /backend

# Run bash script
RUN node_install.sh
RUN python_install.sh

# Expose application at PORT
EXPOSE 3300

RUN pwd

# Start the app
CMD ["bun", "src/index.js"]