# Name of flow
name: Deploy to product environment

# The event of github
# When should it (workflows) run?
on:
  # Push to master or main
  # and has type is `closed`, but it isn't enough
  push:
    branches: [master, main]

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      # Check out to repository
      - name: Check to repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install NODEJS
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build website with webpack
      # The directory is build/gui
      - name: Build website
        run: npm run build

      # Prepare AWS Credential
      - name: Prepare AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      # Upload S3
      - name: Upload website to Amazon S3
        run: aws s3 cp ./build/gui s3://${{ secrets.AWS_BUCKET }} --recursive
